name: Update Version Timestamp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Version
        run: echo "TIMESTAMP=$(TZ="Asia/Kolkata" date -u +"%Y-%m-%dT%H:%M:%S%:z" | sed 's/+00:00/+05:30/')`" >> .env
        env:
          TIMESTAMP: $(TZ="Asia/Kolkata" date -u +"%Y-%m-%dT%H:%M:%S%:z" | sed 's/+00:00/+05:30/')`
