name: Update Version Timestamp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Version
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date -u +"%Y-%m-%dT%H:%M:%S%:z" | sed 's/+00:00/+05:30/')
          echo "const version = '$TIMESTAMP';" > version.js
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b update-version # Create a new branch
          git add version.js
          git commit -m "Update version with timestamp"
          
          # Push changes to the new branch
          git push -f origin update-version
          
          git checkout -b main
          git merge origin/update-version
          git push -f origin main
